### ISSUE TITLE
To-do list Sept 9

### ISSUE THREAD

**Issue by yjin27** [yjin27/Experiment#1]
- [ ] Finish CS project
- [ ] PS readings
- [ ] Go to office hours
- [ ] Figure out how to make a pull request!
